/**************************************************************************************************
* @Author:    Kuldeep Parihar 
* @Date:      06/02/2023
* @Description: This method will handle AccountTrigger queries in Bulk. 
* @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
***************************************************************************************************/
public class cm_AccountTriggerProvider {

}