/**************************************************************************************************
* @Author:    Kuldeep Parihar 
* @Date:      06/02/2023
* @Description: This method will handle Buissness Logic for Account Object
* @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
***************************************************************************************************/
public without sharing class cm_AccountTriggerHandler {

    
     
}